var mongoose=require('mongoose')
const videoSchema=mongoose.Schema({
    categoryid:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:"category"
    },
    subcategoryid:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:"subcategory"
    },
    genreid:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:"genre"
    },
   title:{
    type:"string",
    required:true
   },
   description:{
    type:"string",
    required:true
   },
   launched_year:{
    type:"number",
    required:true
   },
   thumbnail:{
    type:"string",
    required:true
   },
   videourl:{
    type:"string",
    required:true
   }
    },{
    timestamps:{
        createdAt:"created_on",
        updatedAt:"updated_on",
    }
})
module.exports=mongoose.model("video",videoSchema)